// First, I create an array that contains the number of colours. This will be
// useful later
var buttonColours = ["red", "blue", "green", "yellow"];

var gamePattern = []; // This variable will contain the random sequence generated by de game
var userClickedPattern = []; // This variable will contain the sequence of selected button by the user

var started = false; // Some functions change if the game has started
var level = 0; // The number of the level will set the length of the sequence
var showing = false; // State of the sequence showing function

// This listener will start the game
$(document).on("keypress", function() {
  if (!started) {
    nextSequence();
    started = true;
  }
});

// This listener will animate the pressed buttons by the user and play sound,
// then it verifies if the pressed button corresponds to the sequence
$(".btn").click(function() {

  if (!showing) {
    // The id of each button is the corresponding color
    var userChosenColour = $(this).attr("id");

    // Add the pressed button to the user sequence
    if (started) {
      userClickedPattern.push(userChosenColour);
    }

    playSound(userChosenColour);
    animatePress(userChosenColour);

    checkAnswer(level);
  }

});

// This function generates a new position in the gamePattern by randomly select
// a number between 0-4 and finding the correspond colour in buttonColours
function nextSequence() {

  var randomNumber = Math.floor(Math.random() * 4);
  var randomChosenColour = buttonColours[randomNumber];
  gamePattern.push(randomChosenColour);

  // The h1 is updated to say the current level
  level += 1;
  $("h1").text("Level " + level);

  // Show the sequence
  for (var j=0; j<level; j++) {

    doSetTimeout(j, gamePattern);

  }

}

// Show the sequence animation
function doSetTimeout(j, gamePattern) {

  showing = true;
  setTimeout(function() {
    // This is the animation of the buttons in the game sequence
    $("#" + gamePattern[j]).fadeOut(100).fadeIn(100);
    playSound(gamePattern[j]);

    if ((j+1)==gamePattern.length) {
      showing = false;
    }

  }, 500 * j);

}

// This function only plays sound depending on the button pressed
function playSound(name) {
  var sound = new Audio("sounds/" + name + ".mp3");
  sound.play();
}

// This is the animation when the user press a button
function animatePress(currentColour) {
  $("#" + currentColour).addClass("pressed");
  setTimeout(function () {
    $("#" + currentColour).removeClass("pressed");
  }, 100);
}



function checkAnswer(currentLevel) {

  var igual = false;

  // This for loop verifies if the psequence introduced by the user is correct
  // after each selection
  for (var k=0; k<userClickedPattern.length; k++) {

    if (userClickedPattern[k]==gamePattern[k]) {
      igual = true;
    } else {
      igual = false;
      break;
    }

  }

  // If the user finished selecting the sequence:
  if (userClickedPattern.length==currentLevel && igual) {
    showing = true;
    // If it's ok, generate a new position in the gamePattern
    setTimeout(function () {
      nextSequence();
      userClickedPattern = [];
    }, 1000);

  } else if (!igual && started) {
    // If it's not ok, game over
    $("body").addClass("game-over");
    setTimeout(function () {
      $("body").removeClass("game-over");
    }, 200);
    playSound("wrong");
    startOver();

    // console.log("wrong");
  }
}

// Restart all variables if game over occurs
function startOver() {
  $("h1").text("Game Over, Press Any Key to Restart");
  started = false;
  level = 0;
  gamePattern = [];
  userClickedPattern = [];
}

